name: Release
on:
  push:
    ignore-tags:
      - "releases/**"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Install poetry
        run: pipx install poetry

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: "poetry"

      - run: poetry install
        working-directory: .github/release

      - run: poetry run release
        working-directory: .github/release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_LOG_LEVEL: DEBUG
