name: Release
on:
  push:
    ignore-tags:
      - "releases/**"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Install release.py
        run: pipx install .

      - run: release "$PWD/release.py#The script" "README.md"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_LOG_LEVEL: DEBUG
